### ISSUE TITLE
Delete this file: it’s not used

### ISSUE THREAD

**Issue by robinwhittleton** [johnrambow/margaret-wilson_the-able-mclaughlins#1]
https://github.com/johnrambow/margaret-wilson_the-able-mclaughlins/blob/9e1211399feacf5994741f243188a0e198f8ce5d/images/a9546ba5-6191-4e04-e209-d22a10e7d0d7%20(2).jpg%EF%80%BAZone.Identifier#L1-L4

**Comment by johnrambow** [comment]
Thx -- done.
