### ISSUE TITLE
Missing .gitignore file

### ISSUE THREAD

**Issue by robinwhittleton** [johnrambow/margaret-wilson_the-able-mclaughlins#2]
Can you copy in https://raw.githubusercontent.com/standardebooks/tools/master/se/data/templates/gitignore with the filename `.gitignore` (note the `.`) to the base directory.

**Comment by johnrambow** [comment]
OK, this is now uploaded.

**Comment by johnrambow** [comment]
I uploaded it by hand, which may not have been the right way to do so. Then that same file was downloaded, and caused a couple lint errors. Is this something I can simply ignore? Should I re-create the gitignore file locally, perhaps?
![image](https://user-images.githubusercontent.com/86328757/144917611-8e8f355e-c533-4d8d-bebb-d1a65cbb747d.png)

**Comment by robinwhittleton** [comment]
My fault. These are created automatically by the template process but aren’t committed / uploaded; I’d blanked on that 🤦‍♂️ You’re welcome to drop the commit that adds this file, or just remove it in another commit.
