### ISSUE TITLE
Horticultural Adviser seems like a magazine?

### ISSUE THREAD

**Issue by robinwhittleton** [johnrambow/margaret-wilson_the-able-mclaughlins#3]
https://github.com/johnrambow/margaret-wilson_the-able-mclaughlins/blob/9e1211399feacf5994741f243188a0e198f8ce5d/src/epub/text/chapter-12.xhtml#L75

If so it needs `<i epub:type="se:name.publication.magazine">`.

**Comment by johnrambow** [comment]
Yeah, I couldn't decide what they were, but magazine sounds likely. I fixed.
