### ISSUE TITLE
David E. Brown needs an abbr element

### ISSUE THREAD

**Issue by robinwhittleton** [johnrambow/margaret-wilson_the-able-mclaughlins#6]
https://github.com/johnrambow/margaret-wilson_the-able-mclaughlins/blob/9e1211399feacf5994741f243188a0e198f8ce5d/src/epub/text/colophon.xhtml#L22

Should be `David <abbr epub:type="z3998:given-name">E.</abbr> Brown`.

**Comment by johnrambow** [comment]
Got it, thx.
