### ISSUE TITLE
Missing transcriber roles

### ISSUE THREAD

**Issue by robinwhittleton** [johnrambow/margaret-wilson_the-able-mclaughlins#7]
https://github.com/johnrambow/margaret-wilson_the-able-mclaughlins/blob/9e1211399feacf5994741f243188a0e198f8ce5d/src/epub/content.opf#L77-L84

Each transcriber needs their own `trc` role, with the `refines` attribute pointing at their own `id`.

**Comment by johnrambow** [comment]
Thanks; should be fixed now.
