### ISSUE TITLE
A few changes to the long description

### ISSUE THREAD

**Issue by robinwhittleton** [johnrambow/margaret-wilson_the-able-mclaughlins#8]
- The entire long description needs to be wrapped in an appropriately escaped `<p>` tag. You can review other productions for examples.
- I’d suggest splitting it into two paragraphs: a plot exposition, and blurb about the author.
- The data range needs word joiner characters before and after the en dash (see https://standardebooks.org/manual/1.6.2/single-page#8.7.7.5)

**Comment by johnrambow** [comment]
OK, I think I got the paragraph tags escaped property, and I added the word joiners to the en dash, before and after. Thx again.
